# Word Embedding using Keras Embedding Layer

## Definition

The **Embedding Layer** in Keras is a trainable neural network layer that converts words (represented as integers) into **dense, low-dimensional vectors**. Unlike pre-trained embeddings (such as Word2Vec or GloVe), the embedding vectors are **learned automatically during model training**.

---

# Why use an Embedding Layer?

Traditional techniques such as **Bag of Words** and **TF-IDF** produce sparse vectors and do not capture semantic meaning.

The Embedding Layer learns dense representations where similar words have similar vectors.

Example:

```
I love NLP

↓

Integer Encoding

↓

[1, 5, 10]

↓

Embedding Layer

↓

[[0.21, -0.43, ...],
 [0.87, 0.15, ...],
 [-0.34, 0.91, ...]]
```

---

# How Embedding Layer Works

The Embedding Layer acts like a lookup table.

Suppose we have a vocabulary of five words:

| Word | Integer |
|-------|---------|
| I | 1 |
| love | 2 |
| NLP | 3 |
| Machine | 4 |
| Learning | 5 |

Initially, the embedding matrix contains random values.

```
Embedding Matrix

Word ID    Embedding

1 → [0.12, 0.43, -0.82]

2 → [-0.45, 0.81, 0.21]

3 → [0.67, -0.15, 0.92]

4 → [0.38, 0.54, -0.18]

5 → [-0.72, 0.16, 0.51]
```

During training, these vectors are updated using backpropagation.

---

# Architecture

```
Text

↓

Tokenization

↓

Integer Encoding

↓

Embedding Layer

↓

Dense Word Vectors

↓

LSTM / GRU / CNN / Transformer

↓

Prediction
```

---

# Example

Sentence

```
I love NLP
```

Integer Encoding

```
[1, 2, 3]
```

Embedding Output (Embedding Dimension = 4)

```
[
 [0.32, -0.15, 0.42, 0.11],
 [0.81, 0.53, -0.24, 0.78],
 [-0.27, 0.92, 0.61, -0.19]
]
```

Each word becomes a dense vector.

---

# Advantages

- Learns embeddings automatically.
- Dense representation.
- Reduces dimensionality.
- Improves neural network performance.
- Suitable for deep learning models.

---

# Disadvantages

- Requires labeled training data.
- Needs sufficient training examples.
- Learned embeddings are task-specific.
- Not reusable across different tasks unless saved.

---

# Embedding Layer vs Word2Vec

| Embedding Layer | Word2Vec |
|-----------------|----------|
| Learns during model training | Pre-trained or separately trained |
| Task-specific embeddings | General-purpose embeddings |
| Integrated into neural networks | Independent embedding model |
| Requires labeled data | Can be trained on unlabeled text |

---

# Embedding Layer vs TF-IDF

| TF-IDF | Embedding Layer |
|---------|-----------------|
| Sparse vectors | Dense vectors |
| Frequency-based | Learned representations |
| No semantic meaning | Captures semantic similarity |
| High dimensional | Low dimensional |

---

# Applications

- Sentiment Analysis
- Spam Detection
- Machine Translation
- Chatbots
- Question Answering
- Text Classification
- Named Entity Recognition
- Text Generation

---

# Interview Definitions

### Embedding Layer

A trainable neural network layer that maps integer-encoded words into dense vector representations.

---

### Embedding Matrix

A trainable matrix where each row corresponds to the embedding of one word in the vocabulary.

---

### Embedding Dimension

The number of numerical features used to represent each word (e.g., 50, 100, 200, 300).

---

# Interview Questions

### What is an Embedding Layer?

An Embedding Layer is a trainable lookup table that converts integer-encoded words into dense vector representations.

---

### Why use an Embedding Layer?

Because it learns semantic word representations automatically during training and provides better features for deep learning models.

---

### Is the Embedding Layer pre-trained?

No. By default, embeddings are initialized randomly and learned during model training. However, it can also be initialized with pre-trained embeddings such as Word2Vec or GloVe.

---

### What is the input to an Embedding Layer?

A sequence of integer-encoded words.

---

### What is the output?

A dense vector for every input word.

---

# Key Takeaway

- The Embedding Layer is a **trainable lookup table**.
- It converts integer-encoded words into **dense vectors**.
- Embeddings are learned automatically through **backpropagation**.
- It is widely used with **LSTM**, **GRU**, **CNN**, and **Transformer** models.
- It is one of the most common methods for representing text in deep learning.

In [1]:
# ===========================================
# Word Embedding using Keras Embedding Layer
# ===========================================

# Import Libraries
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.21.0


In [2]:
# Sample Corpus

sentences = [
    "I love NLP",
    "I love Machine Learning",
    "Deep Learning is amazing",
    "NLP is fun",
    "Machine Learning is awesome"
]

In [3]:
# Tokenization

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index

print(word_index)

{'learning': 1, 'is': 2, 'i': 3, 'love': 4, 'nlp': 5, 'machine': 6, 'deep': 7, 'amazing': 8, 'fun': 9, 'awesome': 10}


In [4]:
# Convert text into integer sequences

sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

[[3, 4, 5], [3, 4, 6, 1], [7, 1, 2, 8], [5, 2, 9], [6, 1, 2, 10]]


In [12]:
#Padding
max_length = max([len(sentence) for sentence in sequences])
X = pad_sequences(
    sequences,
    maxlen = max_length,
    padding = 'post'
)
print(X)

[[ 3  4  5  0]
 [ 3  4  6  1]
 [ 7  1  2  8]
 [ 5  2  9  0]
 [ 6  1  2 10]]


In [13]:
# Vocabulary Size

vocab_size = len(word_index) + 1

print("Vocabulary Size:", vocab_size)

Vocabulary Size: 11


In [14]:
# Create Embedding Layer

embedding_dim = 8

model = Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim
    )
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
# Generate Embeddings

embeddings = model.predict(X)

print(embeddings.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
(5, 4, 8)


Meaning

5 Sentences
4 Words after Padding
8-Dimensional Embedding

In [16]:
# Embedding of First Sentence

print(embeddings[0])

[[-0.00034735  0.02601805 -0.01739603  0.02415912 -0.03124851  0.03470666
  -0.00703549  0.02460046]
 [-0.03764951 -0.04269816  0.0354153  -0.01671129 -0.04653681 -0.01070024
   0.0068155   0.02494068]
 [ 0.01968639 -0.02533543  0.04857451 -0.04619645  0.03208555  0.00578379
   0.04565403 -0.03922822]
 [ 0.03687027 -0.01160171  0.04366069 -0.03282348 -0.02480347  0.03289788
   0.02947995 -0.03184388]]


In [17]:
# Embedding of the word "NLP"

nlp_id = tokenizer.word_index["nlp"]

embedding_weights = model.layers[0].get_weights()[0]

print("Word ID:", nlp_id)

print("Embedding Vector:")

print(embedding_weights[nlp_id])

Word ID: 5
Embedding Vector:
[ 0.01968639 -0.02533543  0.04857451 -0.04619645  0.03208555  0.00578379
  0.04565403 -0.03922822]


In [18]:
# Show embedding of every word

for word, index in tokenizer.word_index.items():
    print(f"{word:12} --> {embedding_weights[index]}")

learning     --> [ 0.02177754  0.02888509 -0.04591257  0.02637304  0.00339618  0.00093781
 -0.00294229 -0.00358049]
is           --> [ 0.01921617 -0.01326584  0.02246762 -0.03682419 -0.00528629  0.01177243
 -0.04130579  0.0129968 ]
i            --> [-0.00034735  0.02601805 -0.01739603  0.02415912 -0.03124851  0.03470666
 -0.00703549  0.02460046]
love         --> [-0.03764951 -0.04269816  0.0354153  -0.01671129 -0.04653681 -0.01070024
  0.0068155   0.02494068]
nlp          --> [ 0.01968639 -0.02533543  0.04857451 -0.04619645  0.03208555  0.00578379
  0.04565403 -0.03922822]
machine      --> [-0.03387405  0.02966653  0.01263279  0.03342379  0.02828158 -0.01125339
  0.02347566  0.03636909]
deep         --> [ 0.03769383 -0.02150856 -0.01460538 -0.01787701  0.00492163  0.00604558
 -0.02744501 -0.01878577]
amazing      --> [ 0.04513928 -0.01731131 -0.04009603  0.01069176 -0.02134899  0.02937056
 -0.04305721 -0.00168926]
fun          --> [-4.1295469e-02 -2.6130749e-02  3.7752092e-05 -2.160240